name: walle
description: Wallpaper App.
version: 1.0.0+1
author: Tirth Patel
environment:
  sdk: ">2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.2
  shared_preferences: ^0.5.12
  url_launcher: ^5.7.1
  sqflite: ^1.3.1+1
  intent: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/